# Generated by Django 2.0.6 on 2018-07-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('emal', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=11)),
                ('password', models.CharField(default='', max_length=30)),
                ('token_value', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('creat_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
