# Generated by Django 2.0.6 on 2018-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0002_auto_20180702_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='creat_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
