# Generated by Django 2.0.6 on 2018-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0004_auto_20180702_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='creat_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
