# Generated by Django 2.0.6 on 2018-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0007_auto_20180702_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='emal',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='password',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='token_value',
            field=models.TextField(max_length=100),
        ),
    ]
