# Generated by Django 2.0.6 on 2018-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0008_auto_20180702_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_verCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emal', models.TextField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=11)),
                ('code', models.TextField(default='', max_length=10)),
                ('status', models.CharField(max_length=3)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('effective_time', models.TextField(max_length=50)),
            ],
        ),
    ]
