# Generated by Django 2.0.6 on 2018-07-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0009_tbl_vercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_vercode',
            name='creat_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_vercode',
            name='effective_time',
            field=models.DateTimeField(),
        ),
    ]
