# Generated by Django 2.0.6 on 2018-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0010_auto_20180703_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='code',
            field=models.TextField(default='', max_length=20),
        ),
    ]
