# Generated by Django 2.0.6 on 2018-07-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiSoftware', '0011_tbl_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='emal',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tbl_vercode',
            old_name='emal',
            new_name='email',
        ),
    ]
